version: '3'
services:
  maintenance:
    build:
      context: .
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    ports:
      - '8000:80'
    environment:
      TZ: 'America/Sao_Paulo'